name: Java CI/CD

on:
  push:
    branches: [ Dev ]
  pull_request:
    branches: [ Dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker Image
      run: docker build -t shipping-service:${{ github.sha }} .
      
    # Falta agregar los  pasos adicionales para el análisis de código estático, pruebas, y despliegue


